import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'


const Layout = ({children}) => {
    return (
        <>
            <Head>
                <title>Dogecoin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                {children}
            </main>

            <Footer />
        </>
    )
}

export default Layout